user:
  name: 20
  email: 80
  password: 120
  avatar_medium: "200x200>"
  avatar_header: "100x100>"
category:
  per_page: 10
word:
  per_page: 20
  MAXIUM_SIZE: 20
answer:
  size: 20
  MIN_ANSWER_NUMBER: 2
